### ISSUE TITLE
Halaman Artikel, Arsip Artikel

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/tema-palanta#21]

**Comment by andifahruddinakas** [comment]
> Sudah masuk PR sebelumnya

OK, karena sy cek berdasarkan issue sj.

**Comment by pandigresik** [comment]
sudah diperbaiki pada PR https://github.com/OpenSID/tema-palanta/pull/39 dan https://github.com/OpenSID/premium/pull/4211/commits/ba24766f017613d8da45b3de8ff3e52f4d25bb97
